import Head from 'next/head'
import Image from 'next/image'
import {useRouter} from 'next/router'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from "react"
import { Grid, GridItem } from '@chakra-ui/react'
import { ArrowBackIcon, ArrowForwardIcon } from '@chakra-ui/icons'


export default function Home() {

  const router = useRouter()
  const [nftCollections, setNFTCollections] = useState();
  const [responseData, setResponseData] = useState();
  const [pageNum, setPageNum] = useState(1);

  useEffect(() => {
    getNFTCollections();
  }, [])


  async function getNFTCollections(num) {
    var searchParams = new URLSearchParams();
    searchParams.set("pageNum", num)
    await fetch("/api/nftCollections?" + searchParams)
      .then(response => response.json())
      .then(data => 
        setResponseData(data)
      )
      .catch((error) => {
        console.error('Error:', error);
      });
  }


  useEffect(() => {
    if (responseData) {
      setNFTCollections(responseData.result)
    }
  }, [responseData])

  function handleClick(name) {
    router.push({
      pathname:'/collection',
      query: {collectionName:name}
    })
  }

  function handlePageClick(num) {
    setPageNum(num)
    setNFTCollections()
    getNFTCollections(num)
  }



  return (  
   <div className={styles.container}>
      <Head>
        <title>N(FTX)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className={styles.main}>
        <h1 className={styles.title}>
          Browse your favorite NFT Collections!
        </h1>
        {nftCollections ?
          <div>
            <Grid w='100%' h='100%' m={5} templateColumns='repeat(4, 1fr)' gap={6} > 
              {nftCollections.collections.map((collection) =>
                <GridItem onClick={() => handleClick(collection.collectionDict.name)} className={styles.card} key={collection.collectionDict.key} w="100%" bg="blue.500" >
                  <img width={150} height={150} src={collection.collectionDict.avatarImageUrl}/>
                  <div className={styles.cardTitle}>
                    {collection.collectionDict.name}
                  </div>
                  
                </GridItem>
              )}
            </Grid>
            <div className={styles.pageNav}>
              {pageNum > 1 &&
                <ArrowBackIcon m={2} onClick={() => handlePageClick(pageNum - 1)}/>
              }
              {(pageNum * 12) <= nftCollections.count &&
                <ArrowForwardIcon onClick={() => handlePageClick(pageNum + 1)} m={2} />
              }
            </div>
          </div>
          :
          <div>
            loading...
          </div>
        }
      </main>

      <footer className={styles.footer}>
        <a
          href="https://zayyanfaizal.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Built by Zayyan Faizal
        </a>
      </footer>
    </div>

  )
}
